# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5314d2573184647e18e917ca37f61bd73228118cec77e67a0dcffde0100be9658040ac28f49aadd9cd3ef1a17146e7498d55f0bb5f6c6ee4253557e2d85960e

test:
  secret_key_base: 19572cffae86c65aaf835b4b12a2d7890efc3f4bbb468fa0988ad0f811ec362f78f2126f61d7a8da00186617cd5c6f3501abd441a0a4622ac5b3ba2e0848cd3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
